export const ROUTES = {
  LOGIN: '/login',
  HOME: '/',
  SEARCH: '/search',
  PROMPT_DETAIL: '/prompt/:slug',
  PROMPT_DETAIL_PATH: (slug) => `/prompt/${slug}`,
  MY_PROMPTS: '/my-prompts',
  MY_PROMPTS_DASHBOARD: '/my-prompts?tab=dashboard',
  MY_PROMPTS_CREATE: '/my-prompts/create',
  MY_PROMPTS_EDIT: (id) => `/my-prompts/${id}/edit`,
  CREATE_PROMPT: '/my-prompts/create',
  BOOKMARKED: '/bookmarked',
  ADMIN_PROMPTS: '/admin/prompts',
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',
  PLAYGROUND: '/playground',
  PLAYGROUND_ROOM: (roomId) => `/playground/${roomId}`,
  SKILLS: '/skills',
  SKILL_CREATE: '/skills/new',
  SKILL_DETAIL: '/skills/:id',
  SKILL_DETAIL_PATH: (id) => `/skills/${id}`,
  SKILL_EDIT: '/skills/:id/edit',
  SKILL_EDIT_PATH: (id) => `/skills/${id}/edit`,
};
export default ROUTES;