"""Create notification tables

Revision ID: 093bc1eda71d
Revises: a3b4c5d6e7f8
Create Date: 2026-04-09 09:13:16.903973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID, JSONB
from enum import Enum

# revision identifiers, used by Alembic.
revision = '093bc1eda71d'
down_revision = 'a3b4c5d6e7f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create notification_groups table
    op.create_table('notification_groups',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_by', UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    
    # Create notifications table
    op.create_table('notifications',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('notification_group_id', UUID(as_uuid=True), nullable=True),
        sa.Column('target_audience', sa.String(length=50), nullable=False),
        sa.Column('target_user_ids', JSONB(), nullable=True),
        sa.Column('is_pinned', sa.Boolean(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['notification_group_id'], ['notification_groups.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    
    # Create user_notifications table
    op.create_table('user_notifications',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', UUID(as_uuid=True), nullable=False),
        sa.Column('notification_id', UUID(as_uuid=True), nullable=False),
        sa.Column('status', sa.Enum('unread', 'read', 'archived', name='notificationstatus'), nullable=False),
        sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'notification_id'),
    )
    
    # Add indexes
    op.create_index(op.f('ix_notifications_notification_group_id'), 'notifications', ['notification_group_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_notification_id'), 'user_notifications', ['notification_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    
    # Remove existing constraints that might interfere
    op.drop_constraint(op.f('uq_user_skill_bookmark'), 'skill_bookmarks', type_='unique')
    op.create_unique_constraint('unique_user_skill_bookmark', 'skill_bookmarks', ['user_id', 'skill_id'])
    op.drop_column('skill_bookmarks', 'updated_at')
    op.drop_constraint(op.f('uq_skill_compilation_agent'), 'skill_compilations', type_='unique')
    op.create_unique_constraint('unique_skill_agent_compilation', 'skill_compilations', ['skill_id', 'agent'])
    op.drop_constraint(op.f('uq_user_skill_vote'), 'skill_votes', type_='unique')
    op.create_unique_constraint('unique_user_skill_vote', 'skill_votes', ['user_id', 'skill_id'])
    op.create_index(op.f('ix_skills_approval_status'), 'skills', ['approval_status'], unique=False)
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.drop_constraint(op.f('skills_created_by_fkey'), 'skills', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop user_notifications table
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_notification_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    
    # Drop notifications table
    op.drop_index(op.f('ix_notifications_notification_group_id'), table_name='notifications')
    op.drop_table('notifications')
    
    # Drop notification_groups table
    op.drop_table('notification_groups')
    
    # Restore previous constraints
    op.create_foreign_key(op.f('skills_created_by_fkey'), 'skills', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_index(op.f('ix_skills_approval_status'), table_name='skills')
    op.drop_constraint('unique_user_skill_vote', 'skill_votes', type_='unique')
    op.create_unique_constraint(op.f('uq_user_skill_vote'), 'skill_votes', ['user_id', 'skill_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('unique_skill_agent_compilation', 'skill_compilations', type_='unique')
    op.create_unique_constraint(op.f('uq_skill_compilation_agent'), 'skill_compilations', ['skill_id', 'agent'], postgresql_nulls_not_distinct=False)
    op.add_column('skill_bookmarks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint('unique_user_skill_bookmark', 'skill_bookmarks', type_='unique')
    op.create_unique_constraint(op.f('uq_user_skill_bookmark'), 'skill_bookmarks', ['user_id', 'skill_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###