"""add_prompt_categories

Revision ID: 10dd1f351afb
Revises: 4c37a2bb85da
Create Date: 2025-12-24 11:51:39.163482
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10dd1f351afb'
down_revision = '4c37a2bb85da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_categories_name'), 'prompt_categories', ['name'], unique=True)
    op.create_index(op.f('ix_prompt_categories_slug'), 'prompt_categories', ['slug'], unique=True)
    # op.drop_constraint(op.f('access_tokens_jti_key'), 'access_tokens', type_='unique')
    # op.create_index(op.f('ix_access_tokens_jti'), 'access_tokens', ['jti'], unique=True)
    # op.create_index(op.f('ix_access_tokens_user_id'), 'access_tokens', ['user_id'], unique=False)
    # op.create_unique_constraint('uq_prompt_votes_user_prompt', 'prompt_votes', ['user_id', 'prompt_id'])
    op.add_column('prompts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prompts_category_id'), 'prompts', ['category_id'], unique=False)
    op.create_foreign_key(None, 'prompts', 'prompt_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # op.drop_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', type_='unique')
    # op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    # op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # op.create_unique_constraint('uq_role_permissions_role_perm', 'role_permissions', ['role_id', 'permission_id'])
    # op.create_unique_constraint('uq_user_roles_user_role', 'user_roles', ['user_id', 'role_id'])
    # op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # op.drop_column('users', 'role')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=32), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_user_roles_user_role', 'user_roles', type_='unique')
    op.drop_constraint('uq_role_permissions_role_perm', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.drop_index(op.f('ix_prompts_category_id'), table_name='prompts')
    op.drop_column('prompts', 'category_id')
    op.drop_constraint('uq_prompt_votes_user_prompt', 'prompt_votes', type_='unique')
    op.drop_index(op.f('ix_access_tokens_user_id'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_jti'), table_name='access_tokens')
    op.create_unique_constraint(op.f('access_tokens_jti_key'), 'access_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_prompt_categories_slug'), table_name='prompt_categories')
    op.drop_index(op.f('ix_prompt_categories_name'), table_name='prompt_categories')
    op.drop_table('prompt_categories')
    # ### end Alembic commands ###

