"""Add picture to users

Revision ID: 22a5edc1668a
Revises: fbe1d8029472
Create Date: 2025-12-24 15:28:09.481933
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a5edc1668a'
down_revision = 'fbe1d8029472'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    # ### end Alembic commands ###
