"""create_chat_tables

Revision ID: 443e5da79ab3
Revises: f1e2d3c4b5a6
Create Date: 2026-04-08 09:24:43.965607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443e5da79ab3'
down_revision = 'f1e2d3c4b5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('source_prompt_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['source_prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_user_id'), 'chat_rooms', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_room_id'), 'chat_messages', ['room_id'], unique=False)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs', postgresql_where='(user_id IS NOT NULL)')
    op.drop_index(op.f('ix_bookmarks_created_at'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_prompt_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_prompt_comments_parent_id'), table_name='prompt_comments')
    op.drop_index(op.f('ix_prompt_comments_user_id'), table_name='prompt_comments')
    op.drop_constraint(op.f('prompt_tags_category_id_fkey'), 'prompt_tags', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_tags', 'prompt_categories', ['category_id'], ['id'])
    op.drop_index(op.f('ix_prompts_content_format'), table_name='prompts')
    op.drop_index(op.f('ix_user_events_prompt_id'), table_name='user_events', postgresql_where='(prompt_id IS NOT NULL)')
    op.drop_index(op.f('ix_user_events_user_type_created'), table_name='user_events')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_user_events_user_type_created'), 'user_events', ['user_id', 'event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_events_prompt_id'), 'user_events', ['prompt_id'], unique=False, postgresql_where='(prompt_id IS NOT NULL)')
    op.create_index(op.f('ix_prompts_content_format'), 'prompts', ['content_format'], unique=False)
    op.drop_constraint(None, 'prompt_tags', type_='foreignkey')
    op.create_foreign_key(op.f('prompt_tags_category_id_fkey'), 'prompt_tags', 'prompt_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_prompt_comments_user_id'), 'prompt_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_prompt_comments_parent_id'), 'prompt_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_prompt_id'), 'bookmarks', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_created_at'), 'bookmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, postgresql_where='(user_id IS NOT NULL)')
    op.drop_index(op.f('ix_chat_messages_room_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_rooms_user_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###