"""add_prompt_views_table

Revision ID: 46d7233375b6
Revises: 22a5edc1668a
Create Date: 2025-12-24 16:48:02.783383
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d7233375b6'
down_revision = '22a5edc1668a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('viewer_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_time_seconds', sa.Integer(), nullable=True),
    sa.Column('scroll_depth_percent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'user_id', name='uq_prompt_view_user'),
    sa.UniqueConstraint('prompt_id', 'viewer_hash', name='uq_prompt_view_hash')
    )
    op.create_index('ix_prompt_views_prompt_id', 'prompt_views', ['prompt_id'], unique=False)
    op.create_index('ix_prompt_views_viewed_at', 'prompt_views', ['viewed_at'], unique=False)
    # op.drop_constraint(op.f('access_tokens_jti_key'), 'access_tokens', type_='unique')
    # op.create_index(op.f('ix_access_tokens_jti'), 'access_tokens', ['jti'], unique=True)
    # op.create_index(op.f('ix_access_tokens_user_id'), 'access_tokens', ['user_id'], unique=False)
    # op.create_unique_constraint('uq_prompt_votes_user_prompt', 'prompt_votes', ['user_id', 'prompt_id'])  # Already exists
    # op.drop_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', type_='unique')
    # op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    # op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # op.create_unique_constraint('uq_role_permissions_role_perm', 'role_permissions', ['role_id', 'permission_id'])
    # op.create_unique_constraint('uq_user_roles_user_role', 'user_roles', ['user_id', 'role_id'])
    # op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # op.drop_column('users', 'role')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=32), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_user_roles_user_role', 'user_roles', type_='unique')
    op.drop_constraint('uq_role_permissions_role_perm', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_prompt_votes_user_prompt', 'prompt_votes', type_='unique')
    op.drop_index(op.f('ix_access_tokens_user_id'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_jti'), table_name='access_tokens')
    op.create_unique_constraint(op.f('access_tokens_jti_key'), 'access_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_prompt_views_viewed_at', table_name='prompt_views')
    op.drop_index('ix_prompt_views_prompt_id', table_name='prompt_views')
    op.drop_table('prompt_views')
    # ### end Alembic commands ###

