"""make_password_nullable

Revision ID: 4c37a2bb85da
Revises: 20251223_0012
Create Date: 2025-12-24 11:22:51.457325
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c37a2bb85da'
down_revision = '20251223_0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('access_tokens_jti_key'), 'access_tokens', type_='unique')
    # op.create_index(op.f('ix_access_tokens_jti'), 'access_tokens', ['jti'], unique=True)
    # op.create_index(op.f('ix_access_tokens_user_id'), 'access_tokens', ['user_id'], unique=False)
    # op.create_unique_constraint('uq_prompt_votes_user_prompt', 'prompt_votes', ['user_id', 'prompt_id'])
    # op.drop_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', type_='unique')
    # op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    # op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # op.create_unique_constraint('uq_role_permissions_role_perm', 'role_permissions', ['role_id', 'permission_id'])
    # op.create_unique_constraint('uq_user_roles_user_role', 'user_roles', ['user_id', 'role_id'])
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=32), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('uq_user_roles_user_role', 'user_roles', type_='unique')
    op.drop_constraint('uq_role_permissions_role_perm', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_prompt_votes_user_prompt', 'prompt_votes', type_='unique')
    op.drop_index(op.f('ix_access_tokens_user_id'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_jti'), table_name='access_tokens')
    op.create_unique_constraint(op.f('access_tokens_jti_key'), 'access_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###

