"""add_prompt_tags

Revision ID: 4f9e9ecacac3
Revises: 10dd1f351afb
Create Date: 2025-12-24 11:57:23.993475
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f9e9ecacac3'
down_revision = '10dd1f351afb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_tags_name'), 'prompt_tags', ['name'], unique=True)
    op.create_index(op.f('ix_prompt_tags_slug'), 'prompt_tags', ['slug'], unique=True)
    op.create_table('prompt_tag_links',
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['prompt_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prompt_id', 'tag_id')
    )
    # op.drop_constraint(op.f('access_tokens_jti_key'), 'access_tokens', type_='unique')
    # op.create_index(op.f('ix_access_tokens_jti'), 'access_tokens', ['jti'], unique=True)
    # op.create_index(op.f('ix_access_tokens_user_id'), 'access_tokens', ['user_id'], unique=False)
    # op.create_unique_constraint('uq_prompt_votes_user_prompt', 'prompt_votes', ['user_id', 'prompt_id'])
    op.alter_column('prompts', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    # op.drop_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', type_='unique')
    # op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    # op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # op.create_unique_constraint('uq_role_permissions_role_perm', 'role_permissions', ['role_id', 'permission_id'])
    # op.create_unique_constraint('uq_user_roles_user_role', 'user_roles', ['user_id', 'role_id'])
    # op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # op.drop_column('users', 'role')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=32), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_user_roles_user_role', 'user_roles', type_='unique')
    op.drop_constraint('uq_role_permissions_role_perm', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.create_unique_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.alter_column('prompts', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.drop_constraint('uq_prompt_votes_user_prompt', 'prompt_votes', type_='unique')
    op.drop_index(op.f('ix_access_tokens_user_id'), table_name='access_tokens')
    op.drop_index(op.f('ix_access_tokens_jti'), table_name='access_tokens')
    op.create_unique_constraint(op.f('access_tokens_jti_key'), 'access_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.drop_table('prompt_tag_links')
    op.drop_index(op.f('ix_prompt_tags_slug'), table_name='prompt_tags')
    op.drop_index(op.f('ix_prompt_tags_name'), table_name='prompt_tags')
    op.drop_table('prompt_tags')
    # ### end Alembic commands ###

