"""Add slug column to prompts table

Revision ID: 6337b7cc2afb
Revises: 545a3a6bdb7d
Create Date: 2025-12-26 17:13:27.198567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6337b7cc2afb'
down_revision = '545a3a6bdb7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('prompt_categories_name_key'), 'prompt_categories', type_='unique')
    op.drop_constraint(op.f('prompt_categories_slug_key'), 'prompt_categories', type_='unique')
    op.drop_index(op.f('ix_prompt_categories_name'), table_name='prompt_categories')
    op.create_index(op.f('ix_prompt_categories_name'), 'prompt_categories', ['name'], unique=True)
    op.drop_index(op.f('ix_prompt_categories_slug'), table_name='prompt_categories')
    op.create_index(op.f('ix_prompt_categories_slug'), 'prompt_categories', ['slug'], unique=True)
    
    op.add_column('prompts', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_prompts_slug'), 'prompts', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_slug'), table_name='prompts')
    op.drop_column('prompts', 'slug')
    
    # Skip prompt_tags operations - schema has changed
    # op.drop_index(op.f('ix_prompt_tags_name'), table_name='prompt_tags')
    # op.create_index(op.f('ix_prompt_tags_name'), 'prompt_tags', ['name'], unique=False)
    # op.create_unique_constraint(op.f('prompt_tags_name_key'), 'prompt_tags', ['name'], postgresql_nulls_not_distinct=False)
    
    op.drop_index(op.f('ix_prompt_categories_slug'), table_name='prompt_categories')
    op.create_index(op.f('ix_prompt_categories_slug'), 'prompt_categories', ['slug'], unique=False)
    op.drop_index(op.f('ix_prompt_categories_name'), table_name='prompt_categories')
    op.create_index(op.f('ix_prompt_categories_name'), 'prompt_categories', ['name'], unique=False)
    op.create_unique_constraint(op.f('prompt_categories_slug_key'), 'prompt_categories', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('prompt_categories_name_key'), 'prompt_categories', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###