"""Add prompt_views table

Revision ID: 7735fd4d5510
Revises: 3216fd64b50b
Create Date: 2025-12-30 15:25:23.796408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7735fd4d5510'
down_revision = '3216fd64b50b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_views_id'), 'prompt_views', ['id'], unique=False)
    op.drop_index(op.f('idx_prompt_votes_is_helpful'), table_name='prompt_votes')
    op.drop_index(op.f('idx_prompt_votes_prompt_id'), table_name='prompt_votes')
    op.drop_index(op.f('idx_prompt_votes_user_id'), table_name='prompt_votes')
    op.create_index(op.f('ix_prompt_votes_id'), 'prompt_votes', ['id'], unique=False)
    op.drop_constraint(op.f('prompt_votes_user_id_fkey'), 'prompt_votes', type_='foreignkey')
    op.drop_constraint(op.f('prompt_votes_prompt_id_fkey'), 'prompt_votes', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_votes', 'prompts', ['prompt_id'], ['id'])
    op.create_foreign_key(None, 'prompt_votes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_votes', type_='foreignkey')
    op.drop_constraint(None, 'prompt_votes', type_='foreignkey')
    op.create_foreign_key(op.f('prompt_votes_prompt_id_fkey'), 'prompt_votes', 'prompts', ['prompt_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('prompt_votes_user_id_fkey'), 'prompt_votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_prompt_votes_id'), table_name='prompt_votes')
    op.create_index(op.f('idx_prompt_votes_user_id'), 'prompt_votes', ['user_id'], unique=False)
    op.create_index(op.f('idx_prompt_votes_prompt_id'), 'prompt_votes', ['prompt_id'], unique=False)
    op.create_index(op.f('idx_prompt_votes_is_helpful'), 'prompt_votes', ['is_helpful'], unique=False)
    op.drop_index(op.f('ix_prompt_views_id'), table_name='prompt_views')
    op.drop_table('prompt_views')
    # ### end Alembic commands ###