"""Add owner FK to prompts

Revision ID: fbe1d8029472
Revises: c4e795334c0d
Create Date: 2025-12-24 15:25:01.461496
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe1d8029472'
down_revision = 'c4e795334c0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_prompts_owner', 'prompts', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_prompts_owner', 'prompts', type_='foreignkey')
    # ### end Alembic commands ###
